{{- if .Values.cronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "accounts-api.fullname" . }}-load-dd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote}}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "accounts-api.selectorLabels" . | nindent 12 }}
        spec:
          containers:
          - name: edmunds-vehicles-sync
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: ['/bin/sh']
            args: ['-c', '/accounts-api edmunds-vehicles-sync && /accounts-api smartcar-sync && /accounts-api search-sync-dds; CODE=$?; echo "edmunds-vehicles-sync and search-sync-dds completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown; exit $CODE;']
            envFrom:
            - configMapRef:
                name: {{ include "accounts-api.fullname" . }}-config
            - secretRef:
                name: {{ include "accounts-api.fullname" . }}-secret
          restartPolicy: OnFailure
{{ end }}          
