replicaCount: 1
image:
  repository: dimozone/accounts-api
  pullPolicy: IfNotPresent
  tag: 77a015a
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  LOG_LEVEL: info
  DB_PORT: 5432
  GRPC_PORT: 8086
  DB_NAME: accounts_api
  PORT: 8080
  JWT_KEY_SET_URL: https://auth.dev.dimo.zone/keys
  MON_PORT: 8888
  DIMO_REGISTRY_CHAIN_ID: 80002
  EMAIL_CODE_DURATION: 5m
  EMAIL_PORT: '587'
  EMAIL_FROM: hello@dimo.co
  DISABLE_CUSTOMER_IO_EVENTS: false
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
    http:
      port: 8080
      targetPort: http
      protocol: TCP
    grpc:
      port: 8086
      targetPort: grpc
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
  - name: grpc
    containerPort: 8086
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '25'
    external-dns.alpha.kubernetes.io/hostname: accounts-api.dev.dimo.zone
  hosts:
    - host: accounts-api.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
