replicaCount: 2
image:
  repository: dimozone/accounts-api
  pullPolicy: IfNotPresent
  tag: 0.1.5
cronJob:
  enabled: false
  schedule: 0 0 * * 0
env:
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DISABLE_CUSTOMER_IO_EVENTS: true
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/limit-rps: '50'
    external-dns.alpha.kubernetes.io/hostname: accounts-api.dimo.zone
  hosts:
    - host: accounts-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
