issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins: ['*']

staticClients:
  - id: hasura-app
    redirectURIs:
      - 'http://localhost:8080/console/oauth2/callback'
    name: 'Hasura App'
    public: true

connectors:
  - type: saml
    id: saml
    name: SAML
    config:
      # SAML-P sign-on endpoint
      ssoURL: https://login.microsoftonline.com/<Directory (tenant) ID>/saml2
      ca: /path/to/saml-ca.pem
      redirectURI: http://localhost:5556/dex/callback
      usernameAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
      emailAttr: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
      groupsAttr: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
      entityIssuer: spn:<client-id>
