// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts           string
	EmailConfirmations string
	Emails             string
	Wallets            string
}{
	Accounts:           "accounts",
	EmailConfirmations: "email_confirmations",
	Emails:             "emails",
	Wallets:            "wallets",
}
