// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// EmailConfirmation is an object representing the database table.
type EmailConfirmation struct {
	Address   string    `boil:"address" json:"address" toml:"address" yaml:"address"`
	AccountID string    `boil:"account_id" json:"account_id" toml:"account_id" yaml:"account_id"`
	ExpiresAt time.Time `boil:"expires_at" json:"expires_at" toml:"expires_at" yaml:"expires_at"`
	Code      string    `boil:"code" json:"code" toml:"code" yaml:"code"`

	R *emailConfirmationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L emailConfirmationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EmailConfirmationColumns = struct {
	Address   string
	AccountID string
	ExpiresAt string
	Code      string
}{
	Address:   "address",
	AccountID: "account_id",
	ExpiresAt: "expires_at",
	Code:      "code",
}

var EmailConfirmationTableColumns = struct {
	Address   string
	AccountID string
	ExpiresAt string
	Code      string
}{
	Address:   "email_confirmations.address",
	AccountID: "email_confirmations.account_id",
	ExpiresAt: "email_confirmations.expires_at",
	Code:      "email_confirmations.code",
}

// Generated where

var EmailConfirmationWhere = struct {
	Address   whereHelperstring
	AccountID whereHelperstring
	ExpiresAt whereHelpertime_Time
	Code      whereHelperstring
}{
	Address:   whereHelperstring{field: "\"accounts_api\".\"email_confirmations\".\"address\""},
	AccountID: whereHelperstring{field: "\"accounts_api\".\"email_confirmations\".\"account_id\""},
	ExpiresAt: whereHelpertime_Time{field: "\"accounts_api\".\"email_confirmations\".\"expires_at\""},
	Code:      whereHelperstring{field: "\"accounts_api\".\"email_confirmations\".\"code\""},
}

// EmailConfirmationRels is where relationship names are stored.
var EmailConfirmationRels = struct {
	Account string
}{
	Account: "Account",
}

// emailConfirmationR is where relationships are stored.
type emailConfirmationR struct {
	Account *Account `boil:"Account" json:"Account" toml:"Account" yaml:"Account"`
}

// NewStruct creates a new relationship struct
func (*emailConfirmationR) NewStruct() *emailConfirmationR {
	return &emailConfirmationR{}
}

func (r *emailConfirmationR) GetAccount() *Account {
	if r == nil {
		return nil
	}
	return r.Account
}

// emailConfirmationL is where Load methods for each relationship are stored.
type emailConfirmationL struct{}

var (
	emailConfirmationAllColumns            = []string{"address", "account_id", "expires_at", "code"}
	emailConfirmationColumnsWithoutDefault = []string{"address", "account_id", "expires_at", "code"}
	emailConfirmationColumnsWithDefault    = []string{}
	emailConfirmationPrimaryKeyColumns     = []string{"address"}
	emailConfirmationGeneratedColumns      = []string{}
)

type (
	// EmailConfirmationSlice is an alias for a slice of pointers to EmailConfirmation.
	// This should almost always be used instead of []EmailConfirmation.
	EmailConfirmationSlice []*EmailConfirmation
	// EmailConfirmationHook is the signature for custom EmailConfirmation hook methods
	EmailConfirmationHook func(context.Context, boil.ContextExecutor, *EmailConfirmation) error

	emailConfirmationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	emailConfirmationType                 = reflect.TypeOf(&EmailConfirmation{})
	emailConfirmationMapping              = queries.MakeStructMapping(emailConfirmationType)
	emailConfirmationPrimaryKeyMapping, _ = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, emailConfirmationPrimaryKeyColumns)
	emailConfirmationInsertCacheMut       sync.RWMutex
	emailConfirmationInsertCache          = make(map[string]insertCache)
	emailConfirmationUpdateCacheMut       sync.RWMutex
	emailConfirmationUpdateCache          = make(map[string]updateCache)
	emailConfirmationUpsertCacheMut       sync.RWMutex
	emailConfirmationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var emailConfirmationAfterSelectMu sync.Mutex
var emailConfirmationAfterSelectHooks []EmailConfirmationHook

var emailConfirmationBeforeInsertMu sync.Mutex
var emailConfirmationBeforeInsertHooks []EmailConfirmationHook
var emailConfirmationAfterInsertMu sync.Mutex
var emailConfirmationAfterInsertHooks []EmailConfirmationHook

var emailConfirmationBeforeUpdateMu sync.Mutex
var emailConfirmationBeforeUpdateHooks []EmailConfirmationHook
var emailConfirmationAfterUpdateMu sync.Mutex
var emailConfirmationAfterUpdateHooks []EmailConfirmationHook

var emailConfirmationBeforeDeleteMu sync.Mutex
var emailConfirmationBeforeDeleteHooks []EmailConfirmationHook
var emailConfirmationAfterDeleteMu sync.Mutex
var emailConfirmationAfterDeleteHooks []EmailConfirmationHook

var emailConfirmationBeforeUpsertMu sync.Mutex
var emailConfirmationBeforeUpsertHooks []EmailConfirmationHook
var emailConfirmationAfterUpsertMu sync.Mutex
var emailConfirmationAfterUpsertHooks []EmailConfirmationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *EmailConfirmation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *EmailConfirmation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *EmailConfirmation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *EmailConfirmation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *EmailConfirmation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *EmailConfirmation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *EmailConfirmation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *EmailConfirmation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *EmailConfirmation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range emailConfirmationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEmailConfirmationHook registers your hook function for all future operations.
func AddEmailConfirmationHook(hookPoint boil.HookPoint, emailConfirmationHook EmailConfirmationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		emailConfirmationAfterSelectMu.Lock()
		emailConfirmationAfterSelectHooks = append(emailConfirmationAfterSelectHooks, emailConfirmationHook)
		emailConfirmationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		emailConfirmationBeforeInsertMu.Lock()
		emailConfirmationBeforeInsertHooks = append(emailConfirmationBeforeInsertHooks, emailConfirmationHook)
		emailConfirmationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		emailConfirmationAfterInsertMu.Lock()
		emailConfirmationAfterInsertHooks = append(emailConfirmationAfterInsertHooks, emailConfirmationHook)
		emailConfirmationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		emailConfirmationBeforeUpdateMu.Lock()
		emailConfirmationBeforeUpdateHooks = append(emailConfirmationBeforeUpdateHooks, emailConfirmationHook)
		emailConfirmationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		emailConfirmationAfterUpdateMu.Lock()
		emailConfirmationAfterUpdateHooks = append(emailConfirmationAfterUpdateHooks, emailConfirmationHook)
		emailConfirmationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		emailConfirmationBeforeDeleteMu.Lock()
		emailConfirmationBeforeDeleteHooks = append(emailConfirmationBeforeDeleteHooks, emailConfirmationHook)
		emailConfirmationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		emailConfirmationAfterDeleteMu.Lock()
		emailConfirmationAfterDeleteHooks = append(emailConfirmationAfterDeleteHooks, emailConfirmationHook)
		emailConfirmationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		emailConfirmationBeforeUpsertMu.Lock()
		emailConfirmationBeforeUpsertHooks = append(emailConfirmationBeforeUpsertHooks, emailConfirmationHook)
		emailConfirmationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		emailConfirmationAfterUpsertMu.Lock()
		emailConfirmationAfterUpsertHooks = append(emailConfirmationAfterUpsertHooks, emailConfirmationHook)
		emailConfirmationAfterUpsertMu.Unlock()
	}
}

// One returns a single emailConfirmation record from the query.
func (q emailConfirmationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*EmailConfirmation, error) {
	o := &EmailConfirmation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for email_confirmations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all EmailConfirmation records from the query.
func (q emailConfirmationQuery) All(ctx context.Context, exec boil.ContextExecutor) (EmailConfirmationSlice, error) {
	var o []*EmailConfirmation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to EmailConfirmation slice")
	}

	if len(emailConfirmationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all EmailConfirmation records in the query.
func (q emailConfirmationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count email_confirmations rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q emailConfirmationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if email_confirmations exists")
	}

	return count > 0, nil
}

// Account pointed to by the foreign key.
func (o *EmailConfirmation) Account(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.AccountID),
	}

	queryMods = append(queryMods, mods...)

	return Accounts(queryMods...)
}

// LoadAccount allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (emailConfirmationL) LoadAccount(ctx context.Context, e boil.ContextExecutor, singular bool, maybeEmailConfirmation interface{}, mods queries.Applicator) error {
	var slice []*EmailConfirmation
	var object *EmailConfirmation

	if singular {
		var ok bool
		object, ok = maybeEmailConfirmation.(*EmailConfirmation)
		if !ok {
			object = new(EmailConfirmation)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeEmailConfirmation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeEmailConfirmation))
			}
		}
	} else {
		s, ok := maybeEmailConfirmation.(*[]*EmailConfirmation)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeEmailConfirmation)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeEmailConfirmation))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &emailConfirmationR{}
		}
		args[object.AccountID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &emailConfirmationR{}
			}

			args[obj.AccountID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`accounts_api.accounts`),
		qm.WhereIn(`accounts_api.accounts.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for accounts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for accounts")
	}

	if len(accountAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Account = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.EmailConfirmation = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.AccountID == foreign.ID {
				local.R.Account = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.EmailConfirmation = local
				break
			}
		}
	}

	return nil
}

// SetAccount of the emailConfirmation to the related item.
// Sets o.R.Account to related.
// Adds o to related.R.EmailConfirmation.
func (o *EmailConfirmation) SetAccount(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"accounts_api\".\"email_confirmations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"account_id"}),
		strmangle.WhereClause("\"", "\"", 2, emailConfirmationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.Address}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.AccountID = related.ID
	if o.R == nil {
		o.R = &emailConfirmationR{
			Account: related,
		}
	} else {
		o.R.Account = related
	}

	if related.R == nil {
		related.R = &accountR{
			EmailConfirmation: o,
		}
	} else {
		related.R.EmailConfirmation = o
	}

	return nil
}

// EmailConfirmations retrieves all the records using an executor.
func EmailConfirmations(mods ...qm.QueryMod) emailConfirmationQuery {
	mods = append(mods, qm.From("\"accounts_api\".\"email_confirmations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"accounts_api\".\"email_confirmations\".*"})
	}

	return emailConfirmationQuery{q}
}

// FindEmailConfirmation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEmailConfirmation(ctx context.Context, exec boil.ContextExecutor, address string, selectCols ...string) (*EmailConfirmation, error) {
	emailConfirmationObj := &EmailConfirmation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"accounts_api\".\"email_confirmations\" where \"address\"=$1", sel,
	)

	q := queries.Raw(query, address)

	err := q.Bind(ctx, exec, emailConfirmationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from email_confirmations")
	}

	if err = emailConfirmationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return emailConfirmationObj, err
	}

	return emailConfirmationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *EmailConfirmation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no email_confirmations provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailConfirmationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	emailConfirmationInsertCacheMut.RLock()
	cache, cached := emailConfirmationInsertCache[key]
	emailConfirmationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			emailConfirmationAllColumns,
			emailConfirmationColumnsWithDefault,
			emailConfirmationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"accounts_api\".\"email_confirmations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"accounts_api\".\"email_confirmations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into email_confirmations")
	}

	if !cached {
		emailConfirmationInsertCacheMut.Lock()
		emailConfirmationInsertCache[key] = cache
		emailConfirmationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the EmailConfirmation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *EmailConfirmation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	emailConfirmationUpdateCacheMut.RLock()
	cache, cached := emailConfirmationUpdateCache[key]
	emailConfirmationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			emailConfirmationAllColumns,
			emailConfirmationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update email_confirmations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"accounts_api\".\"email_confirmations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, emailConfirmationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, append(wl, emailConfirmationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update email_confirmations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for email_confirmations")
	}

	if !cached {
		emailConfirmationUpdateCacheMut.Lock()
		emailConfirmationUpdateCache[key] = cache
		emailConfirmationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q emailConfirmationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for email_confirmations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for email_confirmations")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EmailConfirmationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailConfirmationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"accounts_api\".\"email_confirmations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, emailConfirmationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in emailConfirmation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all emailConfirmation")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *EmailConfirmation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no email_confirmations provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(emailConfirmationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	emailConfirmationUpsertCacheMut.RLock()
	cache, cached := emailConfirmationUpsertCache[key]
	emailConfirmationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			emailConfirmationAllColumns,
			emailConfirmationColumnsWithDefault,
			emailConfirmationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			emailConfirmationAllColumns,
			emailConfirmationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert email_confirmations, could not build update column list")
		}

		ret := strmangle.SetComplement(emailConfirmationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(emailConfirmationPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert email_confirmations, could not build conflict column list")
			}

			conflict = make([]string, len(emailConfirmationPrimaryKeyColumns))
			copy(conflict, emailConfirmationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"accounts_api\".\"email_confirmations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(emailConfirmationType, emailConfirmationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert email_confirmations")
	}

	if !cached {
		emailConfirmationUpsertCacheMut.Lock()
		emailConfirmationUpsertCache[key] = cache
		emailConfirmationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single EmailConfirmation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *EmailConfirmation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no EmailConfirmation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), emailConfirmationPrimaryKeyMapping)
	sql := "DELETE FROM \"accounts_api\".\"email_confirmations\" WHERE \"address\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from email_confirmations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for email_confirmations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q emailConfirmationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no emailConfirmationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from email_confirmations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_confirmations")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EmailConfirmationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(emailConfirmationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailConfirmationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"accounts_api\".\"email_confirmations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailConfirmationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from emailConfirmation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for email_confirmations")
	}

	if len(emailConfirmationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *EmailConfirmation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEmailConfirmation(ctx, exec, o.Address)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EmailConfirmationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EmailConfirmationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), emailConfirmationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"accounts_api\".\"email_confirmations\".* FROM \"accounts_api\".\"email_confirmations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, emailConfirmationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in EmailConfirmationSlice")
	}

	*o = slice

	return nil
}

// EmailConfirmationExists checks if the EmailConfirmation row exists.
func EmailConfirmationExists(ctx context.Context, exec boil.ContextExecutor, address string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"accounts_api\".\"email_confirmations\" where \"address\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, address)
	}
	row := exec.QueryRowContext(ctx, sql, address)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if email_confirmations exists")
	}

	return exists, nil
}

// Exists checks if the EmailConfirmation row exists.
func (o *EmailConfirmation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EmailConfirmationExists(ctx, exec, o.Address)
}
